### ISSUE TITLE
Question: what language is this project written in?

### ISSUE THREAD

**Issue by PeterHindes** [deep-gaurav/MusicPiped#74]
I would like to try making some pull requests, but i dont know where to start editing this project. Is this a flutter app?

**Comment by deep-gaurav** [comment]
Yes it's a flutter app, But flutter does not provide any kind of background service so that part is coded in Java

If you're interested in making UI changes you can start at lib, and edit flutter files

https://github.com/deep-gaurav/MusicPiped/tree/master/lib

If you're interested in making Android backend changed you can edit java source here,
Almost all of code is in PlayerService.java

https://github.com/deep-gaurav/MusicPiped/tree/master/android/app/src/main/java/me/devsilver/musicpiped 


I can provide insight if you can let me know what part you want to work on

**Comment by PeterHindes** [comment]
I was interested in implimenting play pause and skip controller for Bluetooth headphones and other media control sources

**Comment by deep-gaurav** [comment]
I'll add comment in #73 , closing this issue
